name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Toolchain
      run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Build
      run: cargo build --verbose --target x86_64-unknown-none
    - name: Upload
      uses: actions/upload-artifact@v3.1.2
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: target/x86_64-unknown-none/debug/raisinit
